# Generated by Django 2.2.3 on 2019-07-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_auto_20190730_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_match',
            name='long_url',
            field=models.TextField(),
        ),
    ]
